name: Publish Packages

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore         
    - name: Publish CIS.Service.Client.Interfaces to Nuget
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/CIS.Service.Client.Interfaces/CIS.Service.Client.Interfaces.csproj
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true
          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false
